import {
  Bar,
  BarChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';
import './RevenueChart.css';

const formatCurrency = (value) =>
  `\u20B9${Number(value).toLocaleString('en-IN')}`;

function RevenueChart({ data }) {
  return (
    <section className="chart-card revenue-chart">
      <div className="chart-card__heading">
        <h2>Revenue by channel</h2>
        <p>Revenue generated by each acquisition source.</p>
      </div>

      <div className="chart-card__canvas">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={data} margin={{ top: 8, right: 8, left: 4, bottom: 4 }}>
            <CartesianGrid strokeDasharray="3 3" vertical={false} />
            <XAxis dataKey="acquisitionChannel" tickLine={false} axisLine={false} />
            <YAxis
              tickFormatter={(value) => `\u20B9${Math.round(value / 1000)}k`}
              tickLine={false}
              axisLine={false}
              width={54}
            />
            <Tooltip formatter={(value) => [formatCurrency(value), 'Revenue']} />
            <Bar dataKey="revenue" fill="#4f46e5" radius={[6, 6, 0, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </div>
    </section>
  );
}

export default RevenueChart;
